services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: github-stats-clickhouse
    ports:
      - "8123:8123" # HTTP interface for queries and admin
      - "9000:9000" # Native TCP interface for clients
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: github_stats
      CLICKHOUSE_USER: github_user
      CLICKHOUSE_PASSWORD: github_pass
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  github-stats:
    build: .
    container_name: github-stats-app
    ports:
      - "8000:8000"
    volumes:
      - github_events_data:/app/downloaded-events
      - github_client_state:/app/state
    environment:
      - DATABASE_BACKEND=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=github_user
      - CLICKHOUSE_PASSWORD=github_pass
      - CLICKHOUSE_DATABASE=github_stats
      - CLIENT_STATE_FILE=/app/state/client-state.json
      - SAVE_EVENTS_TO_FILES=true
      - EVENTS_DIRECTORY=/app/downloaded-events
      - GITHUB_TOKEN=${GITHUB_READ_TOKEN}
    depends_on:
      - "clickhouse"
        # condition: service_healthy
    restart: unless-stopped

volumes:
  clickhouse_data:
    driver: local
  github_events_data:
    driver: local
  github_client_state:
    driver: local
